### ISSUE TITLE
[Bug]: v2.7.1 Payment authorization failed on checkout

### ISSUE THREAD

**Issue by hshanjra** [medusajs/medusa#12399]
### Package.json file

```JSON
{
  "name": "api",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build && ln -s .medusa/server/public/ public",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start --types=false",
    "dev": "medusa develop --types=false",
    "db:migrate": "medusa db:migrate",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "format": "prettier --write .",
    "lint": "eslint ./src ",
    "lint:fix": "eslint ./src --fix ",
    "generate:oas": "medusa-oas oas --type combined --paths ./src/api"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.7.1",
    "@medusajs/cli": "2.7.1",
    "@medusajs/framework": "2.7.1",
    "@medusajs/medusa": "2.7.1",
    "@mercurjs/http-client": "*",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "algoliasearch": "^5.20.2",
    "awilix": "^8.0.1",
    "cloudinary": "^2.6.0",
    "pg": "^8.13.0",
    "resend": "^4.1.2",
    "stripe": "^17.4.0"
  },
  "devDependencies": {
    "@eslint/js": "^9.15.0",
    "@medusajs/medusa-oas-cli": "2.7.1",
    "@medusajs/test-utils": "2.7.1",
    "@mikro-orm/cli": "6.4.3",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@trivago/prettier-plugin-sort-imports": "^4.3.0",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "@types/multer": "^1.4.12",
    "eslint": "^9.15.0",
    "globals": "^15.12.0",
    "jest": "^29.7.0",
    "prettier": "^3.3.3",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "typescript-eslint": "^8.15.0",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.14.0

### Database and its version

PostgreSQL 16.1

### Operating system name and version

Windows 11

### Browser name

Chrome

### What happended?

Encountered an issue during checkout while completing the cart. Although the payment status indicates success on the Stripe dashboard, the order is not being created in the system. Below are the error details for your reference:

```
api:dev: error:   Error was thrown trying to authorize payment session - payses_01JTB0FM7JR1D59PA31YVBGFB1 - Error: You must pass a non-undefined value to the property data of entity PaymentSession.
error:   Payment authorization failed
api:dev: {
api:dev:   date: '2025-05-03T11:30:24.368Z',
api:dev:   name: 'Error',
api:dev:   type: 'payment_authorization_error',
api:dev:   stack: 'Error: Payment authorization failed\n' +
api:dev:     '    at Object.exports.authorizePaymentSessionStep.async.container.container (\mercur\\node_modules\\@medusajs\\core-flows\\src\\payment\\steps\\authorize-payment-session.ts:82:13)\n' +
api:dev:     '    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
api:dev:     '    at async invoke (\mercur\\node_modules\\@medusajs\\workflows-sdk\\src\\utils\\composer\\helpers\\create-step-handler.ts:79:52)\n' +
api:dev:     '    at async Object.handle.invoke (\mercur\\node_modules\\@medusajs\\workflows-sdk\\src\\utils\\composer\\create-step.ts:317:12)\n' +
api:dev:     '    at async DistributedTransaction.handler (\mercur\\node_modules\\@medusajs\\orchestration\\src\\workflow\\workflow-manager.ts:214:16)\n' +
api:dev:     '    at async stepHandler (\mercur\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:984:14)\n' +
api:dev:     '    at async Promise.allSettled (index 0)\n' +
api:dev:     '    at async promiseAll (\mercur\\node_modules\\@medusajs\\utils\\src\\common\\promise-all.ts:27:18)\n' +
api:dev:     '    at async TransactionOrchestrator.executeNext \mercur\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:838:7)\n' +
api:dev:     '    at async executeNext (\mercur\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:1201:14)\n' +
api:dev:     '⮑ sat \mercur\\apps\\backend\\src\\workflows\\cart\\workflows\\split-and-complete-cart.ts: [split-and-complete-cart -> authorize-payment-session-step (invoke)]',
api:dev: http:    POST /store/carts/cart_01JTAYH4MRWRYJ56AAK3QAWYF3/complete ← - (422) - 126.038 ms
api:dev:   message: 'Payment authorization failed',
api:dev:   __isMedusaError: true
api:dev: }
``` 

**Workflow** _**<-- split-and-complete-cart.ts**_

```typescript
import { MARKETPLACE_MODULE } from '#/modules/marketplace'
import { OrderSetWorkflowEvents } from '#/modules/marketplace/types'
import { SELLER_MODULE } from '#/modules/seller'

import {
  Modules,
  OrderStatus,
  OrderWorkflowEvents
} from '@medusajs/framework/utils'
import { parallelize, transform, when } from '@medusajs/framework/workflows-sdk'
import {
  authorizePaymentSessionStep,
  createOrdersStep,
  createRemoteLinkStep,
  emitEventStep,
  reserveInventoryStep,
  updateCartsStep,
  useRemoteQueryStep,
  validateCartPaymentsStep
} from '@medusajs/medusa/core-flows'
import { CartShippingMethodDTO } from '@medusajs/types/dist/cart'
import {
  WorkflowResponse,
  createHook,
  createWorkflow
} from '@medusajs/workflows-sdk'

import { createOrderSetStep, validateCartShippingOptionsStep } from '../steps'
import {
  completeCartFields,
  prepareConfirmInventoryInput,
  prepareLineItemData,
  prepareTaxLinesData
} from '../utils'

type SplitAndCompleteCartWorkflowInput = {
  id: string
}

export const splitAndCompleteCartWorkflow = createWorkflow(
  {
    name: 'split-and-complete-cart',
    idempotent: true
  },
  function (
    input: SplitAndCompleteCartWorkflowInput
  ): WorkflowResponse<{ id: string }> {
    const existingOrderSet = useRemoteQueryStep({
      entry_point: 'order_set',
      fields: ['id', 'cart_id'],
      variables: {
        filters: {
          cart_id: input.id
        }
      },
      list: false
    }).config({ name: 'order-set-query' })

    const orderSet = when({ existingOrderSet }, ({ existingOrderSet }) => {
      return !existingOrderSet
    }).then(() => {
      const cart = useRemoteQueryStep({
        entry_point: 'cart',
        fields: completeCartFields,
        variables: {
          id: input.id
        },
        list: false
      }).config({ name: 'cart-query' })

      const validateCartShippingOptionsInput = transform(
        { cart },
        ({ cart }) => ({
          cart_id: cart.id,
          option_ids: cart.shipping_methods.map(
            (method) => method.shipping_option_id
          )
        })
      )

      const { sellerProducts, sellerShippingOptions } =
        validateCartShippingOptionsStep(validateCartShippingOptionsInput)

      const paymentSessions = validateCartPaymentsStep({ cart })

      createHook('beforePaymentAuthorization', {
        input
      })

      const payment = authorizePaymentSessionStep({
        id: paymentSessions[0].id,
        context: { cart_id: cart.id }
      })

      const { ordersToCreate, sellers, variants } = transform(
        { cart, sellerProducts, sellerShippingOptions },
        ({ cart, sellerProducts, sellerShippingOptions }) => {
          const productSellerMap = new Map<string, string>(
            sellerProducts.map((sp) => [sp.product_id, sp.seller_id])
          )
          const shippingOptionSellerMap = new Map<string, string>(
            sellerShippingOptions.map((sp) => [
              sp.shipping_option_id,
              sp.seller_id
            ])
          )
          const sellerLineItemsMap = new Map<string, any[]>()
          const sellerShippingMethodsMap = new Map<
            string,
            CartShippingMethodDTO
          >()
          const variantsMap = new Map<string, any>()

          cart.items.forEach((item) => {
            const sellerId = productSellerMap.get(item.variant.product_id)!
            const lineItems = sellerLineItemsMap.get(sellerId) || []
            lineItems.push(item)
            sellerLineItemsMap.set(sellerId, lineItems)

            variantsMap.set(item.variant.id, item.variant)
          })

          cart.shipping_methods.forEach((method) => {
            const sellerId = shippingOptionSellerMap.get(
              method.shipping_option_id
            )!
            sellerShippingMethodsMap.set(sellerId, method)
          })

          const sellers = Array.from(sellerLineItemsMap.keys())

          const ordersToCreate = sellers.map((sellerId) => {
            const sm = sellerShippingMethodsMap.get(sellerId)!

            const items = sellerLineItemsMap.get(sellerId)!.map((item) =>
              prepareLineItemData({
                item,
                variant: item.variant,
                unitPrice: item.unit_price,
                compareAtUnitPrice: item.compare_at_unit_price,
                isTaxInclusive: item.is_tax_inclusive,
                quantity: item.quantity,
                metadata: item?.metadata,
                taxLines: item.tax_lines ?? []
              })
            )

            return {
              region_id: cart.region?.id,
              customer_id: cart.customer?.id,
              sales_channel_id: cart.sales_channel_id,
              status: OrderStatus.PENDING,
              email: cart.email,
              currency_code: cart.currency_code,
              shipping_address: cart.shipping_address,
              billing_address: cart.billing_address,
              no_notification: false,
              items,
              shipping_methods: [
                {
                  name: sm.name,
                  description: sm.description,
                  amount: sm.amount,
                  is_tax_inclusive: sm.is_tax_inclusive,
                  shipping_option_id: sm.shipping_option_id,
                  data: sm.data,
                  metadata: sm.metadata,
                  tax_lines: prepareTaxLinesData(sm.tax_lines ?? [])
                }
              ]
            }
          })

          return {
            ordersToCreate,
            sellers,
            variants: Array.from(variantsMap.values())
          }
        }
      )

      const orderSet = createOrderSetStep({
        cart_id: cart.id,
        customer_id: cart.customer_id,
        sales_channel_id: cart.sales_channel_id,
        payment_collection_id: payment.payment_collection_id
      })

      const createdOrders = createOrdersStep(ordersToCreate)

      const reservationItemsData = transform(
        { createdOrders },
        ({ createdOrders }) =>
          createdOrders.reduce<
            {
              variant_id: string
              quantity: number
              id: string
            }[]
          >((acc, order) => {
            acc.push(
              ...order.items!.map((i) => ({
                variant_id: i.variant_id!,
                quantity: i.quantity,
                id: i.id
              }))
            )
            return acc
          }, [])
      )

      const updateCartInput = transform({ cart }, ({ cart }) => ({
        id: cart.id,
        completed_at: new Date()
      }))

      const formatedInventoryItems = transform(
        {
          input: {
            sales_channel_id: cart.sales_channel_id,
            variants,
            items: reservationItemsData
          }
        },
        prepareConfirmInventoryInput
      )

      const links = transform(
        {
          createdOrders,
          sellers,
          orderSet,
          cart
        },
        ({ createdOrders, sellers, orderSet, cart }) => {
          const sellerOrderLinks = createdOrders.map((order, index) => ({
            [SELLER_MODULE]: {
              seller_id: sellers[index]
            },
            [Modules.ORDER]: {
              order_id: order.id
            }
          }))

          const orderSetOrderLinks = createdOrders.map((order) => ({
            [MARKETPLACE_MODULE]: {
              order_set_id: orderSet.id
            },
            [Modules.ORDER]: {
              order_id: order.id
            }
          }))

          const orderPaymentLinks = createdOrders.map((order) => ({
            [Modules.ORDER]: {
              order_id: order.id
            },
            [Modules.PAYMENT]: {
              payment_collection_id: cart.payment_collection.id
            }
          }))

          return [
            ...sellerOrderLinks,
            ...orderSetOrderLinks,
            ...orderPaymentLinks
          ]
        }
      )

      const orderEvents = transform({ createdOrders }, ({ createdOrders }) => ({
        eventName: OrderWorkflowEvents.PLACED,
        data: createdOrders.map((order) => ({
          id: order.id
        }))
      }))

      parallelize(
        createRemoteLinkStep(links),
        reserveInventoryStep(formatedInventoryItems),
        updateCartsStep([updateCartInput]),
        emitEventStep(orderEvents),
        emitEventStep({
          eventName: OrderSetWorkflowEvents.PLACED,
          data: {
            id: orderSet.id
          }
        }).config({ name: 'order-set-event' })
      )

      return orderSet
    })

    const orderSetId = transform(
      { orderSet, existingOrderSet },
      ({ orderSet, existingOrderSet }) =>
        orderSet ? orderSet.id : existingOrderSet.id
    )

    return new WorkflowResponse({ id: orderSetId })
  }
)

``` 

### Expected behavior

Upon successful payment as indicated on the Stripe dashboard, an order should be created in the system without any errors.

### Actual behavior

Despite the payment status showing success on the Stripe dashboard, the system fails to create the order. Instead, it throws a `payment_authorization_error`.

### Link to reproduction repo

https://github.com/mercurjs/mercur

**Comment by trevster344** [comment]
Try deleting the workflows table records. I ran into this issue and no matter what I changed it never showed itself to change. I finally cleared the workflows table and suddenly it worked again.

**Comment by hshanjra** [comment]
Appreciate your help buddy @trevster344 

I discovered a bug with the stripe-connect-provider which is a custom payment provider. Initially, the getPaymentStatus function was only returning the payment status instead of the required data object with status. While I resolved this issue, I encountered a new one where the payment is being canceled unexpectedly.

I suspect I might be doing something wrong, but I can't figure out why this is happening.

**Console Error:**

```
api:dev: error:   Error was thrown trying to authorize payment session - payses_01JTQMAJ6V3E399DB054JKKS7S - Error: An error occurred in cancelPayment: Error: You cannot cancel this PaymentIntent because it has a status of succeeded. Only a PaymentIntent with one of the following statuses may be canceled: requires_payment_method, requires_capture, requires_confirmation, requires_action, processing.
api:dev: error:   Payment authorization failed
api:dev: {
api:dev: http:    POST /store/carts/cart_01JTQM9FKTP570FDQ42EE98493/complete ← - (422) - 2016.224 ms
api:dev:   message: 'Payment authorization failed',
api:dev:   name: 'Error',
api:dev:   stack: 'Error: Payment authorization failed\n' +
api:dev:     '    at Object.exports.authorizePaymentSessionStep.async.container.container (\mercur\\node_modules\\@medusajs\\core-flows\\src\\payment\\steps\\authorize-payment-session.ts:82:13)\n' +
api:dev:     '    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
api:dev:     '    at async invoke (\mercur\\node_modules\\@medusajs\\workflows-sdk\\src\\utils\\composer\\helpers\\create-step-handler.ts:79:52)\n' +
api:dev:     '    at async Object.handle.invoke (\mercur\\node_modules\\@medusajs\\workflows-sdk\\src\\utils\\composer\\create-step.ts:317:12)\n' +
api:dev:     '    at async DistributedTransaction.handler (\mercur\\node_modules\\@medusajs\\orchestration\\src\\workflow\\workflow-manager.ts:214:16)\n' +
api:dev:     '    at async stepHandler (\mercur\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:984:14)\n' +
api:dev:     '    at async Promise.allSettled (index 0)\n' +
api:dev:     '    at async promiseAll (\mercur\\node_modules\\@medusajs\\utils\\src\\common\\promise-all.ts:27:18)\n' +
api:dev:     '    at async TransactionOrchestrator.executeNext (\mercur\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:838:7)\n' +
api:dev:     '    at async executeNext (\mercur\\node_modules\\@medusajs\\orchestration\\src\\transaction\\transaction-orchestrator.ts:1201:14)\n' +
api:dev:     '⮑ sat \mercur\\apps\\backend\\src\\workflows\\cart\\workflows\\split-and-complete-cart.ts: [split-and-complete-cart -> authorize-payment-session-step (invoke)]',
api:dev:   __isMedusaError: true,
api:dev:   type: 'payment_authorization_error',
api:dev:   code: undefined,
api:dev:   date: 2025-05-08T09:41:32.861Z
api:dev: }
``` 


**stripe-connect-provider.tsx**

```typescript
import { getAmountFromSmallestUnit, getSmallestUnit } from '#/shared/utils'
import Stripe from 'stripe'

import {
  ProviderWebhookPayload,
  WebhookActionResult
} from '@medusajs/framework/types'
import {
  AbstractPaymentProvider,
  MedusaError,
  PaymentActions,
  PaymentSessionStatus,
  isPresent
} from '@medusajs/framework/utils'
import { Logger } from '@medusajs/medusa/types'
import {
  AuthorizePaymentInput,
  AuthorizePaymentOutput,
  CancelPaymentInput,
  CancelPaymentOutput,
  CapturePaymentInput,
  CapturePaymentOutput,
  DeletePaymentInput,
  DeletePaymentOutput,
  GetPaymentStatusInput,
  GetPaymentStatusOutput,
  InitiatePaymentInput,
  InitiatePaymentOutput,
  RefundPaymentInput,
  RefundPaymentOutput,
  RetrievePaymentInput,
  RetrievePaymentOutput,
  UpdatePaymentInput,
  UpdatePaymentOutput
} from '@medusajs/types'

import { PaymentIntentOptions } from '../types'

type Options = {
  apiKey: string
  webhookSecret: string
}

abstract class StripeConnectProvider extends AbstractPaymentProvider<Options> {
  private readonly options_: Options
  private readonly client_: Stripe
  private readonly logger_: Logger
  constructor(container, options: Options) {
    super(container)

    this.options_ = options

    this.logger_ = container.logger
    this.client_ = new Stripe(options.apiKey)
  }

  abstract get paymentIntentOptions(): PaymentIntentOptions

  async getPaymentStatus(
    input: GetPaymentStatusInput
  ): Promise<GetPaymentStatusOutput> {
    const id = input.data?.id as string
    const paymentIntent = await this.client_.paymentIntents.retrieve(id)
    const dataResponse = paymentIntent as unknown as Record<string, unknown>

    switch (paymentIntent.status) {
      case 'requires_payment_method':
        if (paymentIntent.last_payment_error) {
          return { status: PaymentSessionStatus.ERROR, data: dataResponse }
        }
        return { status: PaymentSessionStatus.PENDING, data: dataResponse }
      case 'requires_confirmation':
      case 'processing':
        return { status: PaymentSessionStatus.PENDING, data: dataResponse }
      case 'requires_action':
        return {
          status: PaymentSessionStatus.REQUIRES_MORE,
          data: dataResponse
        }
      case 'canceled':
        return { status: PaymentSessionStatus.CANCELED, data: dataResponse }
      case 'requires_capture':
        return { status: PaymentSessionStatus.AUTHORIZED, data: dataResponse }
      case 'succeeded':
        return { status: PaymentSessionStatus.CAPTURED, data: dataResponse }
      default:
        return { status: PaymentSessionStatus.PENDING, data: dataResponse }
    }
  }

  async initiatePayment(
    input: InitiatePaymentInput
  ): Promise<InitiatePaymentOutput> {
    const { amount, currency_code } = input

    const email = input.context?.customer?.email

    const paymentIntentInput: Stripe.PaymentIntentCreateParams = {
      ...this.paymentIntentOptions,
      currency: currency_code,
      amount: getSmallestUnit(amount, currency_code)
    }

    // revisit when you could update customer using initiatePayment
    try {
      const {
        data: [customer]
      } = await this.client_.customers.list({
        email,
        limit: 1
      })

      if (customer) {
        paymentIntentInput.customer = customer.id
      }
    } catch (error) {
      throw this.buildError(
        'An error occurred in initiatePayment when retrieving a Stripe customer',
        error
      )
    }

    if (!paymentIntentInput.customer) {
      try {
        const customer = await this.client_.customers.create({ email })
        paymentIntentInput.customer = customer.id
      } catch (error) {
        throw this.buildError(
          'An error occurred in initiatePayment when creating a Stripe customer',
          error
        )
      }
    }

    try {
      const data = (await this.client_.paymentIntents.create(
        paymentIntentInput
      )) as any

      return {
        id: data.id,
        data
      }
    } catch (error) {
      throw this.buildError(
        'An error occurred in initiatePayment when creating a Stripe payment intent',
        error
      )
    }
  }

  async authorizePayment(
    data: AuthorizePaymentInput
  ): Promise<AuthorizePaymentOutput> {
    return await this.getPaymentStatus(data)
  }

  async cancelPayment({
    data: paymentSessionData
  }: CancelPaymentInput): Promise<CancelPaymentOutput> {
    try {
      const id = paymentSessionData?.id as string

      if (!id) {
        return { data: paymentSessionData }
      }

      const data = (await this.client_.paymentIntents.cancel(id)) as any
      return { data }
    } catch (error) {
      throw this.buildError('An error occurred in cancelPayment', error)
    }
  }

  async capturePayment({
    data: paymentSessionData
  }: CapturePaymentInput): Promise<CapturePaymentOutput> {
    const id = paymentSessionData?.id as string
    try {
      const data = (await this.client_.paymentIntents.capture(id)) as any
      return { data }
    } catch (error) {
      throw this.buildError('An error occurred in capturePayment', error)
    }
  }

  deletePayment(data: DeletePaymentInput): Promise<DeletePaymentOutput> {
    return this.cancelPayment(data)
  }

  async refundPayment({
    data: paymentSessionData,
    amount
  }: RefundPaymentInput): Promise<RefundPaymentOutput> {
    const id = paymentSessionData?.id as string

    try {
      const currency = paymentSessionData?.currency as string
      await this.client_.refunds.create({
        amount: getSmallestUnit(amount, currency),
        payment_intent: id as string
      })
    } catch (e) {
      throw this.buildError('An error occurred in refundPayment', e)
    }

    return { data: paymentSessionData }
  }

  async retrievePayment({
    data: paymentSessionData
  }: RetrievePaymentInput): Promise<RetrievePaymentOutput> {
    try {
      const id = paymentSessionData?.id as string
      const intent = (await this.client_.paymentIntents.retrieve(id)) as any

      intent.amount = getAmountFromSmallestUnit(intent.amount, intent.currency)

      return { data: intent }
    } catch (e) {
      throw this.buildError('An error occurred in retrievePayment', e)
    }
  }

  async updatePayment(input: UpdatePaymentInput): Promise<UpdatePaymentOutput> {
    const { data, amount, currency_code } = input

    const amountNumeric = getSmallestUnit(amount, currency_code)

    if (isPresent(amount) && data?.amount === amountNumeric) {
      return { data }
    }

    try {
      const id = data?.id as string
      const sessionData = (await this.client_.paymentIntents.update(id, {
        amount: amountNumeric
      })) as any

      return { data: sessionData }
    } catch (e) {
      throw this.buildError('An error occurred in updatePayment', e)
    }
  }

  async updatePaymentData(sessionId: string, data: Record<string, unknown>) {
    try {
      // Prevent from updating the amount from here as it should go through
      // the updatePayment method to perform the correct logic
      if (isPresent(data.amount)) {
        throw new MedusaError(
          MedusaError.Types.INVALID_DATA,
          'Cannot update amount, use updatePayment instead'
        )
      }

      return (await this.client_.paymentIntents.update(sessionId, {
        ...data
      })) as any
    } catch (e) {
      throw this.buildError('An error occurred in updatePaymentData', e)
    }
  }

  async getWebhookActionAndData(
    webhookData: ProviderWebhookPayload['payload']
  ): Promise<WebhookActionResult> {
    const event = this.constructWebhookEvent(webhookData)
    const intent = event.data.object as Stripe.PaymentIntent

    const { currency } = intent
    switch (event.type) {
      case 'payment_intent.amount_capturable_updated':
        return {
          action: PaymentActions.AUTHORIZED,
          data: {
            session_id: intent.metadata.session_id,
            amount: getAmountFromSmallestUnit(
              intent.amount_capturable,
              currency
            )
          }
        }
      case 'payment_intent.succeeded':
        return {
          action: PaymentActions.SUCCESSFUL,
          data: {
            session_id: intent.metadata.session_id,
            amount: getAmountFromSmallestUnit(intent.amount_received, currency)
          }
        }
      case 'payment_intent.payment_failed':
        return {
          action: PaymentActions.FAILED,
          data: {
            session_id: intent.metadata.session_id,
            amount: getAmountFromSmallestUnit(intent.amount, currency)
          }
        }
      default:
        return { action: PaymentActions.NOT_SUPPORTED }
    }
  }

  constructWebhookEvent(data: ProviderWebhookPayload['payload']): Stripe.Event {
    const signature = data.headers['stripe-signature'] as string

    return this.client_.webhooks.constructEvent(
      data.rawData as string | Buffer,
      signature,
      this.options_.webhookSecret
    )
  }

  private buildError(message: string, error: Error) {
    return new MedusaError(
      MedusaError.Types.PAYMENT_AUTHORIZATION_ERROR,
      `${message}: ${error}`
    )
  }
}

export default StripeConnectProvider
```

**Comment by trevster344** [comment]
Place console.log statements all throughout the code and line by line trace your way to the culprit. Medusa error stacks sometimes hide the true culprits.

**Comment by turistua** [comment]
We experience the same issue, and it happened very occasionally before and now it happens each second order placement attempt.

We use 2.8.1

**Comment by dtoyoda10** [comment]
I’m also getting an error about the PaymentSession data being undefined when trying to authorize a session. Any ideas on what could be causing this?

**Comment by turistua** [comment]
@dtoyoda10 try checking stripe logs, maybe this helps

**Comment by dtoyoda10** [comment]
Yeah, I checked the stripe logs and the payment was completed successfully, even registered the transaction in stripe.

But I am still facing this kind of issue in storefront.

![Image](https://github.com/user-attachments/assets/ac708128-7f57-4794-b138-6eda0da5d411)

```
api:dev: error:   Error was thrown trying to authorize payment session - payses_01JXHG87MVFYPPBMTJDR7MWBSF - Error: You must pass a non-undefined value to the property data of entity PaymentSession.
api:dev: ❌ ERROR IN WORKFLOW: {
api:dev:   message: 'Payment authorization failed',
api:dev:   name: 'Error',
api:dev:   stack: 'Error: Payment authorization failed\n' +
api:dev:     '    at Object.exports.authorizePaymentSessionStep.async.container.container (/home/dtoyoda10/Projects/dtoyoda10/Quinky/quinky-mercur-turbo/node_modules/@medusajs/core-flows/src/payment/steps/authorize-payment-session.ts:82:13)\n' +
api:dev:     '    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n' +
api:dev:     '    at async invoke (/home/dtoyoda10/Projects/dtoyoda10/Quinky/quinky-mercur-turbo/node_modules/@medusajs/workflows-sdk/src/utils/composer/helpers/create-step-handler.ts:78:52)\n' +
api:dev:     '    at async Object.handle.invoke (/home/dtoyoda10/Projects/dtoyoda10/Quinky/quinky-mercur-turbo/node_modules/@medusajs/workflows-sdk/src/utils/composer/create-step.ts:317:12)\n' +
api:dev:     '    at async DistributedTransaction.handler (/home/dtoyoda10/Projects/dtoyoda10/Quinky/quinky-mercur-turbo/node_modules/@medusajs/orchestration/src/workflow/workflow-manager.ts:214:16)\n' +
api:dev:     '    at async stepHandler (/home/dtoyoda10/Projects/dtoyoda10/Quinky/quinky-mercur-turbo/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:861:20)\n' +
api:dev:     '    at async Promise.allSettled (index 0)\n' +
api:dev:     '    at async promiseAll (/home/dtoyoda10/Projects/dtoyoda10/Quinky/quinky-mercur-turbo/node_modules/@medusajs/utils/src/common/promise-all.ts:27:18)\n' +
api:dev:     '    at async TransactionOrchestrator.executeNext (/home/dtoyoda10/Projects/dtoyoda10/Quinky/quinky-mercur-turbo/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:1008:7)\n' +
api:dev:     '    at async executeNext (/home/dtoyoda10/Projects/dtoyoda10/Quinky/quinky-mercur-turbo/node_modules/@medusajs/orchestration/src/transaction/transaction-orchestrator.ts:1054:14)\n' +
api:dev:     '⮑ sat /home/dtoyoda10/Projects/dtoyoda10/Quinky/quinky-mercur-turbo/apps/backend/src/workflows/cart/workflows/split-and-complete-cart.ts: [split-and-complete-cart -> authorize-payment-session-step (invoke)]',
api:dev:   __isMedusaError: true,
api:dev:   type: 'payment_authorization_error',
api:dev:   code: undefined,
api:dev:   date: 2025-06-12T07:22:00.896Z
api:dev: }
```

Do you have any advice with this issue ?

**Comment by turistua** [comment]
@dtoyoda10 I advice you probably ask the question in mercurjs github - maybe it's connected with issues with their implementation. For me issues like this were resolved after upgrade to medusa 2.8.4

You also can review the workflow steps in medusa admin

**Comment by dtoyoda10** [comment]
@turistua Thanks for the suggestion! I’ll try upgrading to Medusa 2.8.4 and also check the workflow steps in Medusa Admin. If the issue persists, I’ll open a discussion on the MercurJS GitHub. Appreciate the help!

**Comment by AnthonyGhizzo** [comment]
Same on 2.8.7

**Comment by julianengel** [comment]
2.8.7 and the issue still presists. It's gotten as far as refunding the order on strip for some reason....

**Comment by julianengel** [comment]
Started with a completely fresh medusa install to verify. Using the Stripe Payment Plugin. Once the payment form opens, before the user types anything in, the **complete-cart** attempts to run. This creates two issues. 1) it takes up an display ID, and two it throws the `error:   Error was thrown trying to authorize payment session` error. Then the user can enter their details, and it will work, however it will have thrown this error before, taken up the order ID and caused a lot of underlying issues. Medusa 2.8.7, fresh install from the create-medusa-app and using latest postgres and reddis.

**Comment by AhmadNasserAbdelaziz** [comment]
Hello guys, where you able to figure this out ? or implement a workaround ?

**Comment by olivermrbl** [comment]
@AnthonyGhizzo @julianengel @AhmadNasserAbdelaziz, we pushed a range of improvements to the cart-completion flow in 2.8.0, one of them eliminating the risk of this issue with unrecoverable payment sessions happening.

I highly recommend reading through the [release notes](https://github.com/medusajs/medusa/releases/tag/v2.8.0), as they explain why it used to be like this and how it works now. 

If you still experience unexpected behavior after updating, please let me know and we will have a look at it.

**Comment by DevKevvv** [comment]
I am currently using 2.9.0 and received the following error message after selecting “Credit Card” during the payment process; Nothing more, just selected.

Here the log part;

`2025-09-11T10:40:21.976336064Z http:    GET /store/payment-providers?region_id=reg_01K4S7VQ256B6SPE0NDECT8XYH ← - (200) - 37.181 ms
2025-09-11T10:40:36.283729844Z info:    Processing cart.updated which has 0 subscribers
2025-09-11T10:40:36.317281060Z http:    POST /store/carts/cart_01K4W5S3G7FNWXB75F3J5S5677 ← - (200) - 731.218 ms
2025-09-11T10:40:36.427502656Z http:    GET /store/carts/cart_01K4W5S3G7FNWXB75F3J5S5677?fields=%2Aitems%2C%20%2Aregion%2C%20%2Aitems.product%2C%20%2Aitems.variant%2C%20%2Aitems.thumbnail%2C%20%2Aitems.metadata%2C%20%2Bitems.total%2C%20%2Apromotions%2C%20%2Bshipping_methods.name%2C%20%2Bshipping_address.metadata%2C%20%2Bbilling_address.metadata%2C ← - (200) - 88.171 ms
2025-09-11T10:40:36.605970455Z http:    GET /store/shipping-options?cart_id=cart_01K4W5S3G7FNWXB75F3J5S5677&fields=%2Bservice_zone.fulfllment_set.type%2C%2Aservice_zone.fulfillment_set.location.address ← - (200) - 170.010 ms
2025-09-11T10:40:38.398666112Z info:    Processing cart.updated which has 0 subscribers
2025-09-11T10:40:38.451292452Z http:    POST /store/carts/cart_01K4W5S3G7FNWXB75F3J5S5677/shipping-methods ← - (200) - 841.314 ms
2025-09-11T10:40:38.579438169Z http:    GET /store/carts/cart_01K4W5S3G7FNWXB75F3J5S5677?fields=%2Aitems%2C%20%2Aregion%2C%20%2Aitems.product%2C%20%2Aitems.variant%2C%20%2Aitems.thumbnail%2C%20%2Aitems.metadata%2C%20%2Bitems.total%2C%20%2Apromotions%2C%20%2Bshipping_methods.name%2C%20%2Bshipping_address.metadata%2C%20%2Bbilling_address.metadata%2C ← - (200) - 103.731 ms
2025-09-11T10:41:03.970537973Z http:    POST /store/payment-collections ← - (200) - 109.602 ms
2025-09-11T10:41:04.574581043Z http:    POST /store/payment-collections/pay_col_01K4W5TMDYE17HFBTET0QK0G5P/payment-sessions ← - (200) - 593.397 ms
2025-09-11T10:41:04.705658097Z http:    GET /store/carts/cart_01K4W5S3G7FNWXB75F3J5S5677?fields=%2Aitems%2C%20%2Aregion%2C%20%2Aitems.product%2C%20%2Aitems.variant%2C%20%2Aitems.thumbnail%2C%20%2Aitems.metadata%2C%20%2Bitems.total%2C%20%2Apromotions%2C%20%2Bshipping_methods.name%2C%20%2Bshipping_address.metadata%2C%20%2Bbilling_address.metadata%2C ← - (200) - 122.236 ms
2025-09-11T10:41:05.172485879Z http:    POST /hooks/payment/stripe_stripe ← - (200) - 9.667 ms
2025-09-11T10:41:10.229939636Z info:    Processing payment.webhook_received which has 2 subscribers
2025-09-11T10:41:12.174890049Z error:   Error was thrown trying to authorize payment session - payses_01K4W5TMHP0VHN7TCTEWGQZ61Z - Error: Session: payses_01K4W5TMHP0VHN7TCTEWGQZ61Z was not authorized with the provider.`

type = payment_intent.created -> this is the webhook that the system received earlier.

However, this error does not affect the payment function. I am able to authorize and “simulate” credit card payments in the sandbox. The transaction was “captured” in stripe and also in medusa.. Not yet tested in production.

But there also seems to be a problem with the capture. After Stripe receives confirmation from the client, the admin sends two more v1/payment_intents/.../capture POSTs.

`{
  "error": {
    "code": "payment_intent_unexpected_state",
    "doc_url": "https://stripe.com/docs/error-codes/payment-intent-unexpected-state",
    "message": "This PaymentIntent could not be captured because it has already been captured.",
    "payment_intent": {… 41 items},
    "request_log_url": "https://dashboard.stripe.com/test/logs/req_WuXFXuLv5943e4?t=1757587353",
    "type": "invalid_request_error"
  }
}
`

**Comment by Yujink0624** [comment]
@julianengel I ran into the same issue you described, and it turned out I had more webhook events registered than what Medusa recommends in their documentation [here](https://docs.medusajs.com/resources/commerce-modules/payment/payment-provider/stripe). 
After I removed some events and kept just these three:

- payment_intent.amount_capturable_updated
- payment_intent.succeeded
- payment_intent.payment_failed

The "payment authorization failed" error was resolved.nCould you check which webhook events you're currently using?
