### ISSUE TITLE
Single product in multiple collections + images to variants

### ISSUE THREAD

**Issue by MedusaNick** [medusajs/medusa#1370]
**Wishes for product page from a current user**
- Would like to be able to put a single product in multiple collections via Admin
- Would like to be able to add images to individual variants

@akarimin

**Comment by adrien2p** [comment]
For the image it could be selected from the product images or create a new product images, that way when you choose a variant you can select the image to be active in the slider to?

**Comment by almousa1990** [comment]
It would be great to have these feature. It is a common use case to have a single product in multiple collections (clothing, summer collection, etc…)

**Comment by lithiumlab** [comment]
product variant image/s is a must for some industries like phone devices. highly desired feature.

**Comment by olivermrbl** [comment]
> Would like to be able to put a single product in multiple collections via Admin
This is already supported in the product create / update flow

> Would like to be able to add images to individual variants
We'll most likely be adding support for images on variants in Q3.

cc @lithiumlab @almousa1990

**Comment by almousa1990** [comment]
@olivermrbl the current version of the product model allows one collection per product.

`  @Column({ type: "text", nullable: true })
  collection_id: string | null

  @ManyToOne(() => ProductCollection)
  @JoinColumn({ name: "collection_id" })
  collection: ProductCollection
`

**Comment by nntan2002** [comment]
i cant find products in collections medusajs api
**
![image](https://user-images.githubusercontent.com/62198480/187423439-07f71891-b947-4c3a-9d85-3daba91faaae.png)
**

**Comment by thngdude** [comment]
When referring to Q3 for variant images, does that mean it's currently WIP? Looking very much forward to this feature as well.

**Comment by aihdeveloper** [comment]
Any status for the variant images feature? Appreciate all the hard work!

**Comment by RegisHubelia** [comment]
+1 - being able to somehow link images with variants is missing.  I'll be working on something as we have an urgent need for this - but it's probably better to have this as a feature to begin with...

**Comment by lithiumlab** [comment]
I have submitted this as a feature days ago. See https://github.com/medusajs/medusa/discussions/2807

**Comment by Dovydastc** [comment]
Waiting for an update on this!

**Comment by olivermrbl** [comment]
Last week, we published an [RFC detailing the concept of a product category](https://github.com/medusajs/medusa/discussions/2873). We will follow up with one centered around the relationship between products and categories. But I can reveal now, that the current proposal introduces a many-to-many relationship allowing you to have multiple categories per product and vice versa. 

With respect to variant images, we are yet to plan that feature. I expect to be able to share details in late Jan or early Feb.

**Comment by alex-brukhty** [comment]
+1 for variant images, thanks

**Comment by AlexTechNoir** [comment]
As a temporary workaround we can set the tags (that will serve as collections) to products and then filter the products by specifying the array of tags' ids in the query, like this:

`http://localhost:9000/store/products?tags[]={id_of_tag_as_collection}&tags[]={id_of_another_tag_as_collection}`

In Admin, the same tag id is set respectively to the same tag title

**Comment by Frioo** [comment]
Would love to see variant images!

**Comment by teddyboirin** [comment]
Someone can give us visibility about how this feature can be developed ? maybe she's already WIP ?

**Comment by microCloudCode** [comment]
variant images! +1

**Comment by ghost** [comment]
Any updates here? Interested in this feature as well.

**Comment by trashken** [comment]
+1 variant images

**Comment by hampusboas** [comment]
+1 variant images

**Comment by trashken** [comment]
Found a plugin for this: 

[https://medusajs.com/plugins/medusa-plugin-variant-images/](https://medusajs.com/plugins/medusa-plugin-variant-images/)

**Comment by adrien2p** [comment]
Seems like this issue have been resolved. 

I apologize for the delayed response.

Please don't hesitate to re-open the issue (or create a new one) if you still need a resolution or an answer.

Thanks ❤️

**Comment by alinjie** [comment]
@adrien2p Do you have any link to where this was resolved? I cannot seem to find it in the changelog.

**Comment by adrien2p** [comment]
We have introduced the categories a few months back which allows you to organise your product in different categories and allows more granular control.

For the variant image, it looks like a plugin has been made

**Comment by AbhiAbhiAbhiAbhi** [comment]
I added this plugin https://medusajs.com/plugins/medusa-plugin-variant-images/ in my project. Though the schema is updated, I am not sure from where I can upload the images for the variants!

I have "@medusajs/admin": "7.1.8" version and rebuilt it also, still not seeing anything on the admin dashboard UI. Can anyone help?

**Comment by kshitijmehta** [comment]
@adrien2p I see the `https://github.com/andriinuts/medusa-plugin-variant-images` archived (with not so happy reasons). Any plans on how to take this request further ?

**Comment by alsherif-khalaf** [comment]
> @adrien2p I see the `https://github.com/andriinuts/medusa-plugin-variant-images` archived (with not so happy reasons). Any plans on how to take this request further ?

Why he archived it ?

**Comment by nourr23** [comment]
So we have to use collections as categories and categories as collections ?

**Comment by devtony01** [comment]
Can't someone just edit core and add the same schema for product images for variant images, then adapt the service too. Like this should not take a day

**Comment by devtony01** [comment]
![Screenshot from 2024-08-04 15-33-32](https://github.com/user-attachments/assets/288e8417-5ebb-4aaf-ace1-30f518ca6329)
Building the above for a client and I might be forced to use Saleor or Vendure, Medusa is my first love but I need my client happy

**Comment by hijak** [comment]
reopen this please its totally blocking me moving from prestashop

**Comment by bigangrycrow** [comment]
Glad the plugin author recommended Vendure; Meudsa was a nice newbie trap for a completely barebones slop app but the more I use it the more I'm pulling my hair out. Webdev was a fucking mistake.

**Comment by davidhotar** [comment]
It's disappointing that these features are still not included after 2 years of development. Why is this the case? Is Medusa prioritizing its own B2B partnerships at the expense of community development? Vendure seems like a better choice now.
