### ISSUE TITLE
Concurrency shopping  may cause database transactions to be 'idle in transaction'

### ISSUE THREAD

**Issue by AoiIsMine** [medusajs/medusa#2619]
### Describe the bug

Concurrency shopping  may cause database transactions to be 'idle in transaction'
### System information

Medusa version (including plugins): medusa 1.6.3, medusa-extender 1.7.7
Node.js version: 14.16.0
Database: PostgreSQL 10.4
Operating system: windows 10
Browser (if relevant):

### Steps to reproduce the behavior
jmeter:
1. Thread 50
2. post /store/carts (create cart)
3. post /store/carts/${id}/line-items (add line item)
4. post /store/carts/${id} (update address)
5. post /store/carts/${id}/payment-sessions (create payment sessions)
6. post /store/carts/${id}/complete (complete cart)

### Expected behavior
May occur 10 idle in transaction , transaction connect is full used, so can't do anything.
(Sometimes it doesn't happen, 5 times maybe 1)

### Screenshots
<img width="176" alt="1" src="https://user-images.githubusercontent.com/25073295/202348809-517e52bd-7bfb-4f32-a6df-91b44616b150.png">
<img width="592" alt="3" src="https://user-images.githubusercontent.com/25073295/202348877-b1057ae8-245b-4658-b49c-1b3a96d503fd.png">
<img width="627" alt="5" src="https://user-images.githubusercontent.com/25073295/202349411-20433ac1-48e5-48ca-a17a-8db6d6bd98f8.png">
> -- 
content is 
> 90358	medusa-docker-new	14279	10	postgres		172.18.0.1		51516	2022-11-17 02:12:00.242529+00	2022-11-17 02:12:32.619498+00	2022-11-17 02:12:33.064334+00	2022-11-17 02:12:33.064463+00	Client	ClientRead	idle in transaction		35969	SELECT "Cart"."id" AS "Cart_id", "Cart__customer"."id" AS "Cart__customer_id", "Cart__customer"."created_at" AS "Cart__customer_created_at", "Cart__customer"."updated_at" AS "Cart__customer_updated_at", "Cart__customer"."deleted_at" AS "Cart__customer_deleted_at", "Cart__customer"."email" AS "Cart__customer_email", "Cart__customer"."first_name" AS "Cart__customer_first_name", "Cart__customer"."last_name" AS "Cart__customer_last_name", "Cart__customer"."billing_address_id" AS "Cart__customer_billing_address_id", "Cart__customer"."phone" AS "Cart__customer_phone", "Cart__customer"."has_account" AS "Cart__customer_has_account", "Cart__customer"."metadata" AS "Cart__customer_metadata" FROM "cart" "Cart" LEFT JOIN "customer" "Cart__customer" ON "Cart__customer"."id"="Cart"."customer_id" AND ("Cart__customer"."deleted_at" IS NULL) WHERE ( "Cart"."id" IN ($1) ) AND ( "Cart"."deleted_at" IS NULL )	client backend
> 

> query: 'COMMIT' has 8 times
<img width="474" alt="4" src="https://user-images.githubusercontent.com/25073295/202349464-1b6bb964-3092-44f9-859a-479520f453bf.png">

* Another situation is update cart and create payment sessions
<img width="290" alt="6" src="https://user-images.githubusercontent.com/25073295/202643706-0185eb65-f42a-42ac-b668-77d6e81279ad.png">
<img width="745" alt="7" src="https://user-images.githubusercontent.com/25073295/202643718-c69c7dcf-18ce-449e-b88c-38d5c13fab95.png">

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

**Comment by AoiIsMine** [comment]
@olivermrbl 😭

**Comment by olivermrbl** [comment]
@AoiIsMine We are currently wrapping up a couple of PRs (#2612) that might resolve your issues. 

We will get back asap with our findings 👍

**Comment by AoiIsMine** [comment]
@olivermrbl ,Thank you for your reply
I don't know 2612(split shopping to little step) is useful to solve this problem.
You can try replay the problem, it look like transaction not commit or rollback,so other transaction is wait for lock release. 
may be transaction started before it was commit.
may be transaction error abort not yet stop then begin agin.
i don't know real reason,i hope your can find it ,
Look forward to your reply, thank u~

**Comment by adrien2p** [comment]
Hey there, i believe that it should be resolved by the latest perf improvements and later on by the improvements will make on the transaction management. Already, the perf improvements will allow the transactions to be released quicker an therefor will not hold a lock for a an extended period of time. Let us know when the release come out.

Ps: depending on the number of concurrency you are expected you should also look into clustering and database scaling as the available connections pool for the database is 10 by default if i am right

**Comment by AoiIsMine** [comment]
@adrien2p
Thank you for your reply.
I probably know what you mean.
Maybe releasing transactions faster and adding database connections can solve the current problem, but will it happen if you increase the concurrency?
The real reason is why the transaction does not continue to execute and there is no deadlock.
I have limited ability, i can't analyze the real reason.so come here for help.
Look forward to your reply.

**Comment by adrien2p** [comment]
Deadlocks are another subject, it generally happen when two running transactions are tying to update the same data and both are waiting the other transaction to be released before being able to commit. 

Also, long running transactions can end up holding lock for an extended period of time and make it easier to have concurrent transactions trying to update the same data. E.g it is a fake one but just for the idea, a customer update a cart and change the billing address, at the same time an admin update the customer address as well which will update his active cart. In such case when they are concurrent those two actions can block each other and in that case we can clearly see that it is not really a bug but more of a case to manage, and this can be why you see an end point becoming idempotent and having multiple steps. 

So the perf improvements will just allow to hold the transaction for less time and therefore reduce the risk of such behavior, but the real fix is the last one mentioned which is to find the culprit and understanding it to fix it.

Another point is that you can't have an infinite number of concurrent users targeting the server each sec. You have to know when and how to scale and not forgetting that scaling is not about just one part of your infra. And this is why i originally told you about the performance improvements we are working on which will allow to support more concurrent requests as well as a better response time and other points 😅 I hope that all those info will help you and let me know otherwise

**Comment by AoiIsMine** [comment]
@adrien2p
Thank you for your patient answer.
I see what you mean. I may limit concurrency.
But I still don't know the real reason. I made a simple test:
begin; a update x row; wait(do nothing); state is idle in transaction.
begin; b update x row; state is activity.
a commit, b will continue.
if b do select,and wait(do nothing); state is idle in transaction.
Picture above error is that all transactions are idle in transaction

So I don't know why they don't continue. Is the code interrupted? Or the database throws an error? But why not roll back?
In my understanding, a transaction that has been waiting must be deadlocked, or it should continue to execute.
So I'm confused. o(╥﹏╥)o

**Comment by adrien2p** [comment]
the transaction can be idle for multiple reasons:
If in your transaction block you do the following:

- SELECT * FROM user
- js loop for post-processing
- return users

here, you should see it like the following:

- **START TRANSACTION**
  - SELECT * FROM user
  - js loop for post-processing
  - UPDATE user SET ...
  - return users
- **COMMIT**

Basically, the transaction is committed once everything is done.

The idea behind the transaction is to ensure atomicity, and therefore in a lot of cases you don't want the following:

- **START TRANSACTION**
  -  SELECT * FROM user
- **COMMIT**
- do some post-processing
- **START TRANSACTION**
  -  UPDATE user SET ...
- **COMMIT**

In the last example (very basic and not real, but just for the idea), if everything was in a single transaction it would mean that if one of the transaction blocks you have to revert the previous one manually.

One thing that I have fixed and allow a boost of performance allow the transactions to be released quickly and also reduce the idle time in the middle.

Hope that the explanation are understandable, let me know

**Comment by AoiIsMine** [comment]
@adrien2p
Thank you for your reply.
Maybe I didn't describe my problem well. I can't understand your explanation.
your mean is large transactions contain many small transactions,that's why happen idle in trasaction?

**Comment by adrien2p** [comment]
What I meant is that an idle transaction can, among other thing, indicate that a transaction (start with begin) has been opened, but nothing is happening. This can be link to the fact that in a transaction block we have the queries but also some other actions not related to the database. In other word, between 2 queries in a transaction block, if nothing is happening the transaction become idle. So, yes the performance boost allows the transaction to be idle for a smaller amount of time. 

Do you think that your idle transaction are happening for another reason ? Cause it can be different reason

**Comment by AoiIsMine** [comment]
@adrien2p
oh,i see. but i think my problem is not what you said.
your example will wait some time, but it will continue do someting.
my example always idle in transaction,these transaction why not conitnue or rollback or do something.

**Comment by adrien2p** [comment]
In that case it can also be a lock, but you can see that by querying the locks to see if there is some deadlocks. Otherwise indeed only the timeout will release them

**Comment by AoiIsMine** [comment]
@adrien2p
yeap,at the first i think happen deadlock,but i try deadlock sql, db will throw error(because db configure deadlock timeout)
but project not throw deadlock error,so i don't konw these transaction why not continue

**Comment by AoiIsMine** [comment]
The project throws some errors during concurrency:
eg: Query runner already released. Cannot run queries anymore, 
ERROR: could not serialize access due to read/write dependencies among transactions
(but i think db will do rollback)

**Comment by AoiIsMine** [comment]
Thank you for your time. I will looking forward to hearing form you.

**Comment by olivermrbl** [comment]
@AoiIsMine Closing this issue for now due to inactivity. Let me know if we should re-open :)
